apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-ens7f1-policy 
spec:
  desiredState:
    interfaces:
      - name: br1 
        description: Linux bridge with ens7f1 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false
          dhcp: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: ens7f1
