apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: node2-br1-ens3f1-policy 
spec:
  nodeSelector:
    kubernetes.io/hostname: costco-cl2-node3
  desiredState:
    interfaces:
      - name: br1 
        description: Linux bridge with ens3f1 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false
          dhcp: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: ens3f1
